apiVersion: v1
entries:
  mysql:
  - annotations:
      category: Database
      images: |
        - name: mysql
          image: docker.io/bitnami/mysql:8.0.36-debian-12-r8
        - name: mysqld-exporter
          image: docker.io/bitnami/mysqld-exporter:0.15.1-debian-12-r8
        - name: os-shell
          image: docker.io/bitnami/os-shell:12-debian-12-r16
      licenses: Apache-2.0
    apiVersion: v2
    appVersion: 8.0.36
    created: "2024-04-17T11:35:42.548281+05:30"
    dependencies:
    - name: common
      repository: oci://registry-1.docker.io/bitnamicharts
      tags:
      - bitnami-common
      version: 2.x.x
    description: MySQL is a fast, reliable, scalable, and easy to use open source
      relational database system. Designed to handle mission-critical, heavy-load
      production applications.
    digest: 52945c346b17fc221cc3ecd9eaf23400ac92dbe33df12bddf3033589679da383
    home: https://bitnami.com
    icon: https://bitnami.com/assets/stacks/mysql/img/mysql-stack-220x234.png
    keywords:
    - mysql
    - database
    - sql
    - cluster
    - high availability
    maintainers:
    - name: VMware, Inc.
      url: https://github.com/bitnami/charts
    name: mysql
    sources:
    - https://github.com/bitnami/charts/tree/main/bitnami/mysql
    urls:
    - file:///Users/rishabha/Desktop/Projects/helm-charts/charts/mysql/mysql-9.22.0.tgz
    version: 9.22.0
generated: "2024-04-17T11:35:42.54647+05:30"
